name: CI

on:
  pull_request:

jobs:
  test-node:
    runs-on: self-hosted
    timeout-minutes: 10

    strategy:
      matrix:
        node-version:
          - 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
